
[workspace]

[package]
edition = "2021"
name = "stm32h7b0-qspi-examples"
version = "0.1.0"
license = "Apache-2.0"
publish = false

[dependencies]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "b57ca947", features = ["defmt", "stm32h7b0vb", "time-driver-tim2", "exti", "memory-x", "unstable-pac", "chrono"] }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "b57ca947", features = ["platform-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "b57ca947", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }

defmt = "1.0.1"
defmt-rtt = "1.0.0"

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = { version = "0.7.0", features = ["set-sp", "set-vtor"]}
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

display-driver = { version = "0.1.0", path = "../../display-driver" }
display-driver-qspi = { version = "0.1.0", path = "../../buses/qspi" }
display-driver-st77916 = { version = "0.1.0", path = "../../panels/st77916" }
tjpgd-rs = { version = "0.1.0", git = "https://github.com/decaday/tjpgd-rs.git", rev = "b2feafee" }

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3 # <-
overflow-checks = false # <-

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3 # <-
overflow-checks = false # <-

[package.metadata.embassy]
build = [
  { target = "thumbv7em-none-eabi", artifact-dir = "out/examples/stm32h7b0" }
]
