#![allow(non_camel_case_types)]

pub use display_driver_mipidcs::PanelSpec;
use display_driver::panel::initseq::InitStep;
use crate::consts::*;

/// Display Specification Trait for ST77916
pub trait St77916Spec: PanelSpec {
    /// Command2 Page sequence
    /// 
    /// This page is enabled when:
    /// - CSC1 (0xF0) = 0x01
    /// - CSC2 (0xF1) = 0x01
    const COMMAND2_PAGE: &'static [InitStep<'static>];

    /// Positive Voltage Gamma Control (0xE0) - 14 bytes
    ///
    /// The Gamma Page is enabled when:
    /// - CSC1 (0xF0) = 0x02
    const GAMCTRP1_PARAMS: [u8; 14];

    /// Negative Voltage Gamma Control (0xE1) - 14 bytes
    const GAMCTRN1_PARAMS: [u8; 14];

    /// GIP Command Page sequence
    /// 
    /// This page is enabled when:
    /// - CSC1 (0xF0) = 0x10
    /// - CSC4 (0xF3) = 0x10
    const GIP_PAGE: &'static [InitStep<'static>];
}

/// NT150XV 1.5 inch QSPI Round Display
pub struct NT150XV;

impl PanelSpec for NT150XV {
    const PHYSICAL_WIDTH: u16 = 360;
    const PHYSICAL_HEIGHT: u16 = 360; 
    const PHYSICAL_X_OFFSET: u16 = 0;
    const PHYSICAL_Y_OFFSET: u16 = 0;
    const INVERTED: bool = true;
    const BGR: bool = false;
}

impl St77916Spec for NT150XV {
    const COMMAND2_PAGE: &'static [InitStep<'static>] = &[
        InitStep::CommandWithParams(VRHPS, &[0x69]),
        InitStep::CommandWithParams(VRHNS, &[0x4A]),
        InitStep::CommandWithParams(VCOMS, &[0x2F]),
        InitStep::CommandWithParams(0xB3, &[0x01]),
        InitStep::CommandWithParams(0xB4, &[0x69]),
        InitStep::CommandWithParams(STEP14S, &[0x45]),
        InitStep::CommandWithParams(STEP23S, &[0xAB]),
        InitStep::CommandWithParams(SBSTS, &[0x41]),
        InitStep::CommandWithParams(0xB8, &[0x86]),
        InitStep::CommandWithParams(0xB9, &[0x15]),
        InitStep::CommandWithParams(TCONS, &[0x00]),
        InitStep::CommandWithParams(RGBVBP, &[0x08]),
        InitStep::CommandWithParams(RGBHBP, &[0x08]),
        InitStep::CommandWithParams(RGBSET, &[0x00]),
        InitStep::CommandWithParams(0xBE, &[0x00]),
        InitStep::CommandWithParams(0xBF, &[0x07]),
        InitStep::CommandWithParams(FRCTRA1, &[0x80]),
        InitStep::CommandWithParams(FRCTRA2, &[0x10]),
        InitStep::CommandWithParams(FRCTRA3, &[0x37]),
        InitStep::CommandWithParams(FRCTRB1, &[0x80]),
        InitStep::CommandWithParams(FRCTRB2, &[0x10]),
        InitStep::CommandWithParams(FRCTRB3, &[0x37]),
        InitStep::CommandWithParams(PWRCTRA1, &[0xA9]),
        InitStep::CommandWithParams(PWRCTRA2, &[0x41]),
        InitStep::CommandWithParams(PWRCTRA3, &[0x01]),
        InitStep::CommandWithParams(PWRCTRB1, &[0xA9]),
        InitStep::CommandWithParams(PWRCTRB2, &[0x41]),
        InitStep::CommandWithParams(PWRCTRB3, &[0x01]),
        InitStep::CommandWithParams(0xCC, &[0x7F]),
        InitStep::CommandWithParams(0xCD, &[0x7F]),
        InitStep::CommandWithParams(0xCE, &[0xFF]),
        InitStep::CommandWithParams(RESSET1, &[0x91]),
        InitStep::CommandWithParams(RESSET2, &[0x68]),
        InitStep::CommandWithParams(RESSET3, &[0x68]),
        InitStep::CommandWithParams(0xF5, &[0x00, 0xA5]),
    ];

    const GAMCTRP1_PARAMS: [u8; 14] = [0xF0, 0x10, 0x18, 0x0D, 0x0C, 0x38, 0x3E, 0x44, 0x51, 0x39, 0x15, 0x15, 0x30, 0x34];
    const GAMCTRN1_PARAMS: [u8; 14] = [0xF0, 0x0F, 0x17, 0x0D, 0x0B, 0x07, 0x3E, 0x33, 0x51, 0x39, 0x15, 0x15, 0x30, 0x34];

    const GIP_PAGE: &'static [InitStep<'static>] = &[
        InitStep::CommandWithParams(0xE0, &[0x08]),
        InitStep::CommandWithParams(0xE1, &[0x00]),
        InitStep::CommandWithParams(0xE2, &[0x00]),
        InitStep::CommandWithParams(0xE3, &[0x00]),
        InitStep::CommandWithParams(0xE4, &[0xE0]),
        InitStep::CommandWithParams(0xE5, &[0x06]),
        InitStep::CommandWithParams(0xE6, &[0x21]),
        InitStep::CommandWithParams(0xE7, &[0x03]),
        InitStep::CommandWithParams(0xE8, &[0x05]),
        InitStep::CommandWithParams(0xE9, &[0x02]),
        InitStep::CommandWithParams(0xEA, &[0xE9]),
        InitStep::CommandWithParams(0xEB, &[0x00]),
        InitStep::CommandWithParams(0xEC, &[0x00]),
        InitStep::CommandWithParams(0xED, &[0x14]),
        InitStep::CommandWithParams(0xEE, &[0xFF]),
        InitStep::CommandWithParams(0xEF, &[0x00]),
        InitStep::CommandWithParams(0xF8, &[0xFF]),
        InitStep::CommandWithParams(0xF9, &[0x00]),
        InitStep::CommandWithParams(0xFA, &[0x00]),
        InitStep::CommandWithParams(0xFB, &[0x30]),
        InitStep::CommandWithParams(0xFC, &[0x00]),
        InitStep::CommandWithParams(0xFD, &[0x00]),
        InitStep::CommandWithParams(0xFE, &[0x00]),
        InitStep::CommandWithParams(0xFF, &[0x00]),
        InitStep::CommandWithParams(0x60, &[0x40]),
        InitStep::CommandWithParams(0x61, &[0x05]),
        InitStep::CommandWithParams(0x62, &[0x00]),
        InitStep::CommandWithParams(0x63, &[0x42]),
        InitStep::CommandWithParams(0x64, &[0xDA]),
        InitStep::CommandWithParams(0x65, &[0x00]),
        InitStep::CommandWithParams(0x66, &[0x00]),
        InitStep::CommandWithParams(0x67, &[0x00]),
        InitStep::CommandWithParams(0x68, &[0x00]),
        InitStep::CommandWithParams(0x69, &[0x00]),
        InitStep::CommandWithParams(0x6A, &[0x00]),
        InitStep::CommandWithParams(0x6B, &[0x00]),
        InitStep::CommandWithParams(0x70, &[0x40]),
        InitStep::CommandWithParams(0x71, &[0x04]),
        InitStep::CommandWithParams(0x72, &[0x00]),
        InitStep::CommandWithParams(0x73, &[0x42]),
        InitStep::CommandWithParams(0x74, &[0xD9]),
        InitStep::CommandWithParams(0x75, &[0x00]),
        InitStep::CommandWithParams(0x76, &[0x00]),
        InitStep::CommandWithParams(0x77, &[0x00]),
        InitStep::CommandWithParams(0x78, &[0x00]),
        InitStep::CommandWithParams(0x79, &[0x00]),
        InitStep::CommandWithParams(0x7A, &[0x00]),
        InitStep::CommandWithParams(0x7B, &[0x00]),
        InitStep::CommandWithParams(0x80, &[0x48]),
        InitStep::CommandWithParams(0x81, &[0x00]),
        InitStep::CommandWithParams(0x82, &[0x07]),
        InitStep::CommandWithParams(0x83, &[0x02]),
        InitStep::CommandWithParams(0x84, &[0xD7]),
        InitStep::CommandWithParams(0x85, &[0x04]),
        InitStep::CommandWithParams(0x86, &[0x00]),
        InitStep::CommandWithParams(0x87, &[0x00]),
        InitStep::CommandWithParams(0x88, &[0x48]),
        InitStep::CommandWithParams(0x89, &[0x00]),
        InitStep::CommandWithParams(0x8A, &[0x09]),
        InitStep::CommandWithParams(0x8B, &[0x02]),
        InitStep::CommandWithParams(0x8C, &[0xD9]),
        InitStep::CommandWithParams(0x8D, &[0x04]),
        InitStep::CommandWithParams(0x8E, &[0x00]),
        InitStep::CommandWithParams(0x8F, &[0x00]),
        InitStep::CommandWithParams(0x90, &[0x48]),
        InitStep::CommandWithParams(0x91, &[0x00]),
        InitStep::CommandWithParams(0x92, &[0x0B]),
        InitStep::CommandWithParams(0x93, &[0x02]),
        InitStep::CommandWithParams(0x94, &[0xDB]),
        InitStep::CommandWithParams(0x95, &[0x04]),
        InitStep::CommandWithParams(0x96, &[0x00]),
        InitStep::CommandWithParams(0x97, &[0x00]),
        InitStep::CommandWithParams(0x98, &[0x48]),
        InitStep::CommandWithParams(0x99, &[0x00]),
        InitStep::CommandWithParams(0x9A, &[0x0D]),
        InitStep::CommandWithParams(0x9B, &[0x02]),
        InitStep::CommandWithParams(0x9C, &[0xDD]),
        InitStep::CommandWithParams(0x9D, &[0x04]),
        InitStep::CommandWithParams(0x9E, &[0x00]),
        InitStep::CommandWithParams(0x9F, &[0x00]),
        InitStep::CommandWithParams(0xA0, &[0x48]),
        InitStep::CommandWithParams(0xA1, &[0x00]),
        InitStep::CommandWithParams(0xA2, &[0x06]),
        InitStep::CommandWithParams(0xA3, &[0x02]),
        InitStep::CommandWithParams(0xA4, &[0xD6]),
        InitStep::CommandWithParams(0xA5, &[0x04]),
        InitStep::CommandWithParams(0xA6, &[0x00]),
        InitStep::CommandWithParams(0xA7, &[0x00]),
        InitStep::CommandWithParams(0xA8, &[0x48]),
        InitStep::CommandWithParams(0xA9, &[0x00]),
        InitStep::CommandWithParams(0xAA, &[0x08]),
        InitStep::CommandWithParams(0xAB, &[0x02]),
        InitStep::CommandWithParams(0xAC, &[0xD8]),
        InitStep::CommandWithParams(0xAD, &[0x04]),
        InitStep::CommandWithParams(0xAE, &[0x00]),
        InitStep::CommandWithParams(0xAF, &[0x00]),
        InitStep::CommandWithParams(0xB0, &[0x48]),
        InitStep::CommandWithParams(0xB1, &[0x00]),
        InitStep::CommandWithParams(0xB2, &[0x0A]),
        InitStep::CommandWithParams(0xB3, &[0x02]),
        InitStep::CommandWithParams(0xB4, &[0xDA]),
        InitStep::CommandWithParams(0xB5, &[0x04]),
        InitStep::CommandWithParams(0xB6, &[0x00]),
        InitStep::CommandWithParams(0xB7, &[0x00]),
        InitStep::CommandWithParams(0xB8, &[0x48]),
        InitStep::CommandWithParams(0xB9, &[0x00]),
        InitStep::CommandWithParams(0xBA, &[0x0C]),
        InitStep::CommandWithParams(0xBB, &[0x02]),
        InitStep::CommandWithParams(0xBC, &[0xDC]),
        InitStep::CommandWithParams(0xBD, &[0x04]),
        InitStep::CommandWithParams(0xBE, &[0x00]),
        InitStep::CommandWithParams(0xBF, &[0x00]),
        InitStep::CommandWithParams(0xC0, &[0x10]),
        InitStep::CommandWithParams(0xC1, &[0x47]),
        InitStep::CommandWithParams(0xC2, &[0x56]),
        InitStep::CommandWithParams(0xC3, &[0x65]),
        InitStep::CommandWithParams(0xC4, &[0x74]),
        InitStep::CommandWithParams(0xC5, &[0x88]),
        InitStep::CommandWithParams(0xC6, &[0x99]),
        InitStep::CommandWithParams(0xC7, &[0x01]),
        InitStep::CommandWithParams(0xC8, &[0xBB]),
        InitStep::CommandWithParams(0xC9, &[0xAA]),
        InitStep::CommandWithParams(0xD0, &[0x10]),
        InitStep::CommandWithParams(0xD1, &[0x47]),
        InitStep::CommandWithParams(0xD2, &[0x56]),
        InitStep::CommandWithParams(0xD3, &[0x65]),
        InitStep::CommandWithParams(0xD4, &[0x74]),
        InitStep::CommandWithParams(0xD5, &[0x88]),
        InitStep::CommandWithParams(0xD6, &[0x99]),
        InitStep::CommandWithParams(0xD7, &[0x01]),
        InitStep::CommandWithParams(0xD8, &[0xBB]),
        InitStep::CommandWithParams(0xD9, &[0xAA]),
    ];
}

/// JC3636W518C 1.8 inch QSPI Round Display
pub struct JC3636W518C;

impl PanelSpec for JC3636W518C {
    const PHYSICAL_WIDTH: u16 = 360;
    const PHYSICAL_HEIGHT: u16 = 360; 
    const PHYSICAL_X_OFFSET: u16 = 0;
    const PHYSICAL_Y_OFFSET: u16 = 0;
    const INVERTED: bool = true;
    const BGR: bool = false;
}

impl St77916Spec for JC3636W518C {
    const COMMAND2_PAGE: &'static [InitStep<'static>] = &[
        InitStep::CommandWithParams(VRHPS, &[0x56]),
        InitStep::CommandWithParams(VRHNS, &[0x4D]),
        InitStep::CommandWithParams(VCOMS, &[0x24]),
        InitStep::CommandWithParams(0xB4, &[0x87]),
        InitStep::CommandWithParams(STEP14S, &[0x44]),
        InitStep::CommandWithParams(STEP23S, &[0x8B]),
        InitStep::CommandWithParams(SBSTS, &[0x40]),
        InitStep::CommandWithParams(0xB8, &[0x86]),
        InitStep::CommandWithParams(TCONS, &[0x00]),
        InitStep::CommandWithParams(RGBVBP, &[0x08]),
        InitStep::CommandWithParams(RGBHBP, &[0x08]),
        InitStep::CommandWithParams(RGBSET, &[0x00]),
        InitStep::CommandWithParams(FRCTRA1, &[0x80]),
        InitStep::CommandWithParams(FRCTRA2, &[0x10]),
        InitStep::CommandWithParams(FRCTRA3, &[0x37]),
        InitStep::CommandWithParams(FRCTRB1, &[0x80]),
        InitStep::CommandWithParams(FRCTRB2, &[0x10]),
        InitStep::CommandWithParams(FRCTRB3, &[0x37]),
        InitStep::CommandWithParams(PWRCTRA1, &[0xA9]),
        InitStep::CommandWithParams(PWRCTRA2, &[0x41]),
        InitStep::CommandWithParams(PWRCTRA3, &[0x01]),
        InitStep::CommandWithParams(PWRCTRB1, &[0xA9]),
        InitStep::CommandWithParams(PWRCTRB2, &[0x41]),
        InitStep::CommandWithParams(PWRCTRB3, &[0x01]),
        InitStep::CommandWithParams(RESSET1, &[0x91]),
        InitStep::CommandWithParams(RESSET2, &[0x68]),
        InitStep::CommandWithParams(RESSET3, &[0x68]),
        InitStep::CommandWithParams(0xF5, &[0x00, 0xA5]),
        InitStep::CommandWithParams(VCMOFSET, &[0x4F]),
        InitStep::CommandWithParams(VCMOFNSET, &[0x4F]),
    ];

    const GAMCTRP1_PARAMS: [u8; 14] = [0xF0, 0x0A, 0x10, 0x09, 0x09, 0x36, 0x35, 0x33, 0x4A, 0x29, 0x15, 0x15, 0x2E, 0x34];
    const GAMCTRN1_PARAMS: [u8; 14] = [0xF0, 0x0A, 0x0F, 0x08, 0x08, 0x05, 0x34, 0x33, 0x4A, 0x39, 0x15, 0x15, 0x2D, 0x33];

    const GIP_PAGE: &'static [InitStep<'static>] = &[
        InitStep::CommandWithParams(0xE0, &[0x07]),
        InitStep::CommandWithParams(0xE1, &[0x00]),
        InitStep::CommandWithParams(0xE2, &[0x00]),
        InitStep::CommandWithParams(0xE3, &[0x00]),
        InitStep::CommandWithParams(0xE4, &[0xE0]),
        InitStep::CommandWithParams(0xE5, &[0x06]),
        InitStep::CommandWithParams(0xE6, &[0x21]),
        InitStep::CommandWithParams(0xE7, &[0x01]),
        InitStep::CommandWithParams(0xE8, &[0x05]),
        InitStep::CommandWithParams(0xE9, &[0x02]),
        InitStep::CommandWithParams(0xEA, &[0xDA]),
        InitStep::CommandWithParams(0xEB, &[0x00]),
        InitStep::CommandWithParams(0xEC, &[0x00]),
        InitStep::CommandWithParams(0xED, &[0x0F]),
        InitStep::CommandWithParams(0xEE, &[0x00]),
        InitStep::CommandWithParams(0xEF, &[0x00]),
        InitStep::CommandWithParams(0xF8, &[0x00]),
        InitStep::CommandWithParams(0xF9, &[0x00]),
        InitStep::CommandWithParams(0xFA, &[0x00]),
        InitStep::CommandWithParams(0xFB, &[0x00]),
        InitStep::CommandWithParams(0xFC, &[0x00]),
        InitStep::CommandWithParams(0xFD, &[0x00]),
        InitStep::CommandWithParams(0xFE, &[0x00]),
        InitStep::CommandWithParams(0xFF, &[0x00]),
        InitStep::CommandWithParams(0x60, &[0x40]),
        InitStep::CommandWithParams(0x61, &[0x04]),
        InitStep::CommandWithParams(0x62, &[0x00]),
        InitStep::CommandWithParams(0x63, &[0x42]),
        InitStep::CommandWithParams(0x64, &[0xD9]),
        InitStep::CommandWithParams(0x65, &[0x00]),
        InitStep::CommandWithParams(0x66, &[0x00]),
        InitStep::CommandWithParams(0x67, &[0x00]),
        InitStep::CommandWithParams(0x68, &[0x00]),
        InitStep::CommandWithParams(0x69, &[0x00]),
        InitStep::CommandWithParams(0x6A, &[0x00]),
        InitStep::CommandWithParams(0x6B, &[0x00]),
        InitStep::CommandWithParams(0x70, &[0x40]),
        InitStep::CommandWithParams(0x71, &[0x03]),
        InitStep::CommandWithParams(0x72, &[0x00]),
        InitStep::CommandWithParams(0x73, &[0x42]),
        InitStep::CommandWithParams(0x74, &[0xD8]),
        InitStep::CommandWithParams(0x75, &[0x00]),
        InitStep::CommandWithParams(0x76, &[0x00]),
        InitStep::CommandWithParams(0x77, &[0x00]),
        InitStep::CommandWithParams(0x78, &[0x00]),
        InitStep::CommandWithParams(0x79, &[0x00]),
        InitStep::CommandWithParams(0x7A, &[0x00]),
        InitStep::CommandWithParams(0x7B, &[0x00]),
        InitStep::CommandWithParams(0x80, &[0x48]),
        InitStep::CommandWithParams(0x81, &[0x00]),
        InitStep::CommandWithParams(0x82, &[0x06]),
        InitStep::CommandWithParams(0x83, &[0x02]),
        InitStep::CommandWithParams(0x84, &[0xD6]),
        InitStep::CommandWithParams(0x85, &[0x04]),
        InitStep::CommandWithParams(0x86, &[0x00]),
        InitStep::CommandWithParams(0x87, &[0x00]),
        InitStep::CommandWithParams(0x88, &[0x48]),
        InitStep::CommandWithParams(0x89, &[0x00]),
        InitStep::CommandWithParams(0x8A, &[0x08]),
        InitStep::CommandWithParams(0x8B, &[0x02]),
        InitStep::CommandWithParams(0x8C, &[0xD8]),
        InitStep::CommandWithParams(0x8D, &[0x04]),
        InitStep::CommandWithParams(0x8E, &[0x00]),
        InitStep::CommandWithParams(0x8F, &[0x00]),
        InitStep::CommandWithParams(0x90, &[0x48]),
        InitStep::CommandWithParams(0x91, &[0x00]),
        InitStep::CommandWithParams(0x92, &[0x0A]),
        InitStep::CommandWithParams(0x93, &[0x02]),
        InitStep::CommandWithParams(0x94, &[0xDA]),
        InitStep::CommandWithParams(0x95, &[0x04]),
        InitStep::CommandWithParams(0x96, &[0x00]),
        InitStep::CommandWithParams(0x97, &[0x00]),
        InitStep::CommandWithParams(0x98, &[0x48]),
        InitStep::CommandWithParams(0x99, &[0x00]),
        InitStep::CommandWithParams(0x9A, &[0x0C]),
        InitStep::CommandWithParams(0x9B, &[0x02]),
        InitStep::CommandWithParams(0x9C, &[0xDC]),
        InitStep::CommandWithParams(0x9D, &[0x04]),
        InitStep::CommandWithParams(0x9E, &[0x00]),
        InitStep::CommandWithParams(0x9F, &[0x00]),
        InitStep::CommandWithParams(0xA0, &[0x48]),
        InitStep::CommandWithParams(0xA1, &[0x00]),
        InitStep::CommandWithParams(0xA2, &[0x05]),
        InitStep::CommandWithParams(0xA3, &[0x02]),
        InitStep::CommandWithParams(0xA4, &[0xD5]),
        InitStep::CommandWithParams(0xA5, &[0x04]),
        InitStep::CommandWithParams(0xA6, &[0x00]),
        InitStep::CommandWithParams(0xA7, &[0x00]),
        InitStep::CommandWithParams(0xA8, &[0x48]),
        InitStep::CommandWithParams(0xA9, &[0x00]),
        InitStep::CommandWithParams(0xAA, &[0x07]),
        InitStep::CommandWithParams(0xAB, &[0x02]),
        InitStep::CommandWithParams(0xAC, &[0xD7]),
        InitStep::CommandWithParams(0xAD, &[0x04]),
        InitStep::CommandWithParams(0xAE, &[0x00]),
        InitStep::CommandWithParams(0xAF, &[0x00]),
        InitStep::CommandWithParams(0xB0, &[0x48]),
        InitStep::CommandWithParams(0xB1, &[0x00]),
        InitStep::CommandWithParams(0xB2, &[0x09]),
        InitStep::CommandWithParams(0xB3, &[0x02]),
        InitStep::CommandWithParams(0xB4, &[0xD9]),
        InitStep::CommandWithParams(0xB5, &[0x04]),
        InitStep::CommandWithParams(0xB6, &[0x00]),
        InitStep::CommandWithParams(0xB7, &[0x00]),
        InitStep::CommandWithParams(0xB8, &[0x48]),
        InitStep::CommandWithParams(0xB9, &[0x00]),
        InitStep::CommandWithParams(0xBA, &[0x0B]),
        InitStep::CommandWithParams(0xBB, &[0x02]),
        InitStep::CommandWithParams(0xBC, &[0xDB]),
        InitStep::CommandWithParams(0xBD, &[0x04]),
        InitStep::CommandWithParams(0xBE, &[0x00]),
        InitStep::CommandWithParams(0xBF, &[0x00]),
        InitStep::CommandWithParams(0xC0, &[0x10]),
        InitStep::CommandWithParams(0xC1, &[0x47]),
        InitStep::CommandWithParams(0xC2, &[0x56]),
        InitStep::CommandWithParams(0xC3, &[0x65]),
        InitStep::CommandWithParams(0xC4, &[0x74]),
        InitStep::CommandWithParams(0xC5, &[0x88]),
        InitStep::CommandWithParams(0xC6, &[0x99]),
        InitStep::CommandWithParams(0xC7, &[0x01]),
        InitStep::CommandWithParams(0xC8, &[0xBB]),
        InitStep::CommandWithParams(0xC9, &[0xAA]),
        InitStep::CommandWithParams(0xD0, &[0x10]),
        InitStep::CommandWithParams(0xD1, &[0x47]),
        InitStep::CommandWithParams(0xD2, &[0x56]),
        InitStep::CommandWithParams(0xD3, &[0x65]),
        InitStep::CommandWithParams(0xD4, &[0x74]),
        InitStep::CommandWithParams(0xD5, &[0x88]),
        InitStep::CommandWithParams(0xD6, &[0x99]),
        InitStep::CommandWithParams(0xD7, &[0x01]),
        InitStep::CommandWithParams(0xD8, &[0xBB]),
        InitStep::CommandWithParams(0xD9, &[0xAA]),
    ];
}
